### ISSUE TITLE
Create keystore

### ISSUE THREAD

**Issue by Tobisaninfo** [tipsy/spark-ssl#3]
I'll try to create my own keystore with a cirtificate but the HTTPS Connection doesn't work.
Do you have some idear how to create a proper keystore.
Thanks for helping me.

**Comment by miraenator** [comment]
+1
How did you create the keystore?

**Comment by tipsy** [comment]
I used this: https://docs.oracle.com/cd/E19509-01/820-3503/ggfen/index.html
